name: XPLevel
version: ${project.version}
main: dev.atarim.xplevel.XPLevel
api-version: 1.13
depend: [TitleAPI]
commands:
  skills:
    description: Opens the Skill Menu
  review:
    description: Review a person